import test from 'node:test';
import assert from 'node:assert/strict';
import {
  createBoardRoom,
  addBoardPlayer,
  startBoardMatch,
  applyBoardCommand,
  boardPublicState,
  resetBoardMatch,
} from '../src/rooms/board-game-core.js';

function idFactory() {
  let i = 0;
  return () => `p${++i}`;
}

function tokenFactory() {
  let i = 0;
  return () => `token-${++i}`;
}

function makeRoom(gameType, names) {
  const makeId = idFactory();
  const makeToken = tokenFactory();
  const room = createBoardRoom({ code: '123456', hostKey: 'host-key', gameType, now: 1000 });
  names.forEach((name, index) => {
    addBoardPlayer(room, {
      id: makeId(),
      token: makeToken(),
      name,
      role: index === 0 ? 'host' : 'guest',
      now: 1000 + index,
    });
  });
  return room;
}

test('snakes room starts with 2-4 ready players and rejects a fifth seat', () => {
  const room = makeRoom('snakes', ['أ', 'ب', 'ج', 'د']);
  for (const id of room.order) room.players[id].ready = true;
  assert.throws(() => addBoardPlayer(room, { id: 'p5', token: 't5', name: 'هـ', role: 'guest', now: 1005 }), /room_full/);
  startBoardMatch(room, () => 0.5);
  assert.equal(room.status, 'playing');
  assert.equal(room.game.players.length, 4);
});

test('snakes roll is generated by server rng and only current seat can roll', () => {
  const room = makeRoom('snakes', ['أ', 'ب']);
  for (const id of room.order) room.players[id].ready = true;
  startBoardMatch(room, () => 0.5);
  const actorId = room.order[0];
  const otherId = room.order[1];
  assert.throws(() => applyBoardCommand(room, otherId, { type: 'roll' }, () => 0), /wrong_turn/);
  const result = applyBoardCommand(room, actorId, { type: 'roll' }, () => 0.999999);
  assert.equal(result.event.roll, 6);
  assert.equal(room.game.lastRoll, 6);
});

test('jackaroo requires exactly four ready players before start', () => {
  const room = makeRoom('jackaroo', ['أ', 'ب', 'ج']);
  for (const id of room.order) room.players[id].ready = true;
  assert.throws(() => startBoardMatch(room, () => 0.25), /jackaroo_requires_4_players/);
  addBoardPlayer(room, { id: 'p4', token: 't4', name: 'د', role: 'guest', now: 1004 });
  room.players.p4.ready = true;
  startBoardMatch(room, () => 0.25);
  assert.equal(room.game.players.length, 4);
  assert.equal(room.status, 'playing');
});

test('jackaroo public state exposes viewer hand only and counts for opponents', () => {
  const room = makeRoom('jackaroo', ['أ', 'ب', 'ج', 'د']);
  for (const id of room.order) room.players[id].ready = true;
  startBoardMatch(room, () => 0.3);
  const viewerId = room.order[0];
  const publicState = boardPublicState(room, viewerId);
  assert.deepEqual(publicState.game.hand, room.game.hands[0]);
  assert.deepEqual(publicState.game.handCounts, room.game.hands.map((hand) => hand.length));
  assert.equal('hands' in publicState.game, false);
  assert.equal(JSON.stringify(publicState).includes(room.game.hands[1][0]), false);
});

test('jackaroo server rejects forged out-of-turn play', () => {
  const room = makeRoom('jackaroo', ['أ', 'ب', 'ج', 'د']);
  for (const id of room.order) room.players[id].ready = true;
  startBoardMatch(room, () => 0.4);
  const wrongSeat = (room.game.turn + 1) % 4;
  const wrongId = room.order[wrongSeat];
  assert.throws(() => applyBoardCommand(room, wrongId, { type: 'play_card', cardIndex: 0, action: { type: 'discard' } }, () => 0.4), /wrong_turn/);
});

test('rematch clears game and ready flags but preserves seats', () => {
  const room = makeRoom('snakes', ['أ', 'ب']);
  for (const id of room.order) room.players[id].ready = true;
  startBoardMatch(room, () => 0.5);
  const order = [...room.order];
  resetBoardMatch(room, 5000);
  assert.equal(room.status, 'lobby');
  assert.equal(room.game, null);
  assert.deepEqual(room.order, order);
  assert.ok(room.order.every((id) => room.players[id].ready === false));
});
